export type game = {
  id: number;
  min: string;
  fgm: number;
  fga: number;
  fg_pct: number;
  fg3m: number;
  fg3a: number;
  fg3_pct: number;
  ftm: number;
  fta: number;
  ft_pct: number;
  oreb: number;
  dreb: number;
  reb: number;
  ast: number;
  stl: number;
  blk: number;
  turnover: number;
  pf: number;
  pts: number;
  plus_minus: number;
  player: {
    id: number;
    first_name: string;
    last_name: string;
    position: string;
    height: string;
    weight: string;
    jersey_number: string;
    college: string;
    country: string;
    draft_year: number;
    draft_round: number;
    draft_number: number;
    team_id: number;
  };
  team: {
    id: number;
    conference: string;
    division: string;
    city: string;
    name: string;
    full_name: string;
    abbreviation: string;
  };
  game: {
    id: number;
    date: string;
    season: number;
    status: string;
    period: number;
    time: string;
    postseason: boolean;
    postponed: boolean;
    home_team_score: number;
    visitor_team_score: number;
    datetime: string;
    home_q1: number;
    home_q2: number;
    home_q3: number;
    home_q4: number;
    home_ot1: number | null;
    home_ot2: number | null;
    home_ot3: number | null;
    home_timeouts_remaining: number;
    home_in_bonus: boolean;
    visitor_q1: number;
    visitor_q2: number;
    visitor_q3: number;
    visitor_q4: number;
    visitor_ot1: number | null;
    visitor_ot2: number | null;
    visitor_ot3: number | null;
    visitor_timeouts_remaining: number;
    visitor_in_bonus: boolean;
    ist_stage: boolean | null;
    home_team_id: number;
    visitor_team_id: number;
  };
};
export type event = {
  start: string;
  end: string;
  title: string;
};
